using System;

/*
    This was generated by doing the following:
       -> VS 2015
       -> new project
       -> web -> asp.net web application
       -> Web API
          -> change authentication (on the right) to none
    
    Modification
        -> modifications were made to this controller ONLY to support demo of different functionalities (Get/Put/Post/Delete)

    Purpose:
        -> discuss how Web API is different from regular MVC, what automation is happening, and how to get things started

    Test client:
        -> added a test client to demonstrate functionality of this controller

    Home Controller
        -> added a demo to test/consume this controller

    More info:
        -> CRUD operations (Create, Read, Update, Delete) in Web.Api lingo:

        -> POST is create
        -> GET is read
        -> PUT is update
        -> DELETE is delete
*/

namespace BasicRestApplication.Controllers
{
    using Data;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Http;
    using System.Net.Http;
    using System.Net;
    using ErrorLoggerModel;
    using LoadersNLogic;
    using log4net;
    
    public class ValuesController : ApiController
    {
        private static readonly ILog Log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // POST api/values
        public void Post(ErrorRestViewModel error)
        {
            Log.Debug("POST Request traced");
            ErrorLoggerHandler errorLoggerhandler_ = new ErrorLoggerHandler();
            //call the database to add into database
            try
            {
                errorLoggerhandler_.saveErrorInDB(error);
                
            }catch(Exception ex)
            {
                Log.Debug("Database Save Error: " + ex.Message);
                HttpResponseMessage message = new HttpResponseMessage(HttpStatusCode.InternalServerError);
                message.Content = new StringContent(ex.Message);
                message.ReasonPhrase = "Not able to save the error in DB. Check if application ID is correct.";
                throw new HttpResponseException(message);
                
            }

            
        }
    } 
        
}